### ISSUE TITLE
error in running custom dictionary

### ISSUE THREAD

**Issue by deliapxq** [negar-mokhberian/Moral_Foundation_FrameAxis#3]
Hello there,

I was trying to run the code with a customised dictionary (it's the MFD2.0, but in the exact format as the MFD file, with 'word', 'category' and 'sentiment' as columns in the .csv), but have run into some trouble.

This is the input code:

`python main.py --input_file Test1.csv --output_file OUTPUT2.csv --docs_colname text --dict_type customized`

and the error output as follows:

`Running FrameAxis Moral Foundations scores`
`authority`
`(0,)`
`(0,)`
`C:\Users\...\anaconda3\envs\frameaxis\lib\site-packages\numpy\core\fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)`
`C:\Users\...\anaconda3\envs\frameaxis\lib\site-packages\numpy\core\_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)`
`()`
`care`
`(0,)`
`(0,)`
`()`
`fairness`
`(0,)`
`(0,)`
`()`
`loyalty`
`(0,)`
`(0,)`
`()`
`sanctity`
`(0,)`
`(0,)`
`()`
`Preprocessing column text`
`Let's calculate bias and intensity`
`authority`
`B_T = 0.0`
`Current doc_idx: 0/ Total: 12`
`care`
`B_T = 0.0`
`Current doc_idx: 0/ Total: 12`
`fairness`
`B_T = 0.0`
`Current doc_idx: 0/ Total: 12`
`loyalty`
`B_T = 0.0`
`Current doc_idx: 0/ Total: 12`
`sanctity`
`B_T = 0.0`
`Current doc_idx: 0/ Total: 12`
`total size:  12`
`Traceback (most recent call last):
  File "main.py", line 46, in <module>
    save_path=OUT_CSV_PATH)
  File "C:\Users\...\frameaxis\frameAxis.py", line 252, in get_fa_scores
    print('any NaN in bias?', np.isnan(bias.values).sum())      # Nan means empty docs, we should remove them`
`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

Any help is appreciated, thank you very much :)

**Comment by negar-mokhberian** [comment]
Hi there,
The support for MFD2.0 has been added. Simply set the dict_type as "mfd2" and it should work.
