### ISSUE TITLE
Tab/syntax errors?

### ISSUE THREAD

**Issue by richardhuskey** [negar-mokhberian/Moral_Foundation_FrameAxis#4]
Hello! Thank you so much for sharing this code! Maybe you can help clarify a problem I've run into.

When trying to run the code as shown in the documentation, using python3.7, I get the following error:

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from frameAxis import FrameAxis
  File "/home/rwhuskey/Downloads/Moral_Foundation_FrameAxis-main/frameAxis.py", line 24
    mfs_df = []
              ^
TabError: inconsistent use of tabs and spaces in indentation`

I cleaned up the indentation, see [frameAxis_tabfix.zip](https://github.com/negar-mokhberian/Moral_Foundation_FrameAxis/files/8246811/frameAxis_tabfix.zip). But now get a new error.

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from frameAxis import FrameAxis
  File "/home/rwhuskey/Downloads/Moral_Foundation_FrameAxis-main/frameAxis.py", line 44
    mfd2 = pd.DataFrame(mfs_df)
    ^
SyntaxError: invalid syntax`

Looking at the `frameAxis.py` file, I see the following comment on line 50 `# todo add "mfd2"`. Maybe that explains the error? Is an out of date file posted to GitHub?

Any insights on how to get the code working would be greatly appreciated. Thank you!!

**Comment by negar-mokhberian** [comment]
Hi,

I am sorry for the delay in my response. 
Thank you for bringing this important problem to my attention. I have made some fixes now and hopefully the code will run smoothly for you. 
Please let me know if you face any other problem.
